### ISSUE TITLE
PDF extract finalization steps

### ISSUE THREAD

**Issue by voisardf** [camptocamp/pyramid_oereb#297]
As of today, here are the missing points to get a compliant PDF extract:

## Full PDF:
I got an error for now and no PDF:
```
print_1  | net.sf.jasperreports.engine.JRRuntimeException: net.sf.jasperreports.engine.JRException: Error opening input stream from URL: http://localhost:6543/oereb/image/logo/confederation.
print_1  |      at net.sf.jasperreports.repo.DefaultRepositoryService.getInputStream(DefaultRepositoryService.java:118)
print_1  |      at net.sf.jasperreports.repo.InputStreamPersistenceService.load(InputStreamPersistenceService.java:47)
print_1  |      at net.sf.jasperreports.repo.DefaultRepositoryService.getResource(DefaultRepositoryService.java:159)
print_1  |      at net.sf.jasperreports.repo.RepositoryUtil.findInputStream(RepositoryUtil.java:190)
print_1  |      at net.sf.jasperreports.repo.RepositoryUtil.getBytesFromLocation(RepositoryUtil.java:206)
print_1  |      at net.sf.jasperreports.engine.RenderableUtil.getRenderable(RenderableUtil.java:122)
print_1  |      at net.sf.jasperreports.engine.fill.JRFillImage.evaluateImage(JRFillImage.java:584)
print_1  |      at net.sf.jasperreports.engine.fill.JRFillImage.evaluate(JRFillImage.java:520)
print_1  |      at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:281)
print_1  |      at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:504)
print_1  |      at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillTitle(JRVerticalFiller.java:318)
print_1  |      at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:158)
print_1  |      at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:555)
print_1  |      at net.sf.jasperreports.parts.subreport.SubreportFillPart.fill(SubreportFillPart.java:174)
print_1  |      at net.sf.jasperreports.engine.part.FillPart.fill(FillPart.java:77)
print_1  |      at net.sf.jasperreports.engine.fill.PartReportFiller.fillPart(PartReportFiller.java:400)
print_1  |      at net.sf.jasperreports.engine.fill.PartReportFiller.fillParts(PartReportFiller.java:385)
print_1  |      at net.sf.jasperreports.engine.fill.PartReportFiller.fillFirstGroupHeaders(PartReportFiller.java:344)
print_1  |      at net.sf.jasperreports.engine.fill.PartReportFiller.fillReport(PartReportFiller.java:278)
print_1  |      at net.sf.jasperreports.engine.fill.PartReportFiller.fill(PartReportFiller.java:214)
print_1  |      at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:414)
print_1  |      at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:122)
print_1  |      at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:583)
print_1  |      at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:223)
print_1  |      at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:94)
print_1  |      at org.mapfish.print.MapPrinter.print(MapPrinter.java:125)
print_1  |      at org.mapfish.print.servlet.job.PrintJob$1.run(PrintJob.java:90)
print_1  |      at org.mapfish.print.servlet.job.impl.FilePrintJob.withOpenOutputStream(FilePrintJob.java:31)
print_1  |      at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:87)
print_1  |      at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:32)
print_1  |      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
print_1  |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
print_1  |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
print_1  |      at java.lang.Thread.run(Thread.java:748)
print_1  | Caused by: net.sf.jasperreports.engine.JRException: Error opening input stream from URL: http://localhost:6543/oereb/image/logo/confederation.
print_1  |      at net.sf.jasperreports.engine.util.JRLoader.getInputStream(JRLoader.java:343)
print_1  |      at net.sf.jasperreports.repo.DefaultRepositoryService.getInputStream(DefaultRepositoryService.java:101)
print_1  |      ... 33 common frames omitted
print_1  | Caused by: java.net.ConnectException: Connection refused (Connection refused)
print_1  |      at java.net.PlainSocketImpl.socketConnect(Native Method)
print_1  |      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
print_1  |      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
print_1  |      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
print_1  |      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
print_1  |      at java.net.Socket.connect(Socket.java:589)
print_1  |      at java.net.Socket.connect(Socket.java:538)
print_1  |      at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
print_1  |      at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
print_1  |      at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
print_1  |      at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
print_1  |      at sun.net.www.http.HttpClient.New(HttpClient.java:339)
print_1  |      at sun.net.www.http.HttpClient.New(HttpClient.java:357)
print_1  |      at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
print_1  |      at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
print_1  |      at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
print_1  |      at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
print_1  |      at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
print_1  |      at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
print_1  |      at java.net.URL.openStream(URL.java:1045)
print_1  |      at net.sf.jasperreports.engine.util.JRLoader.getInputStream(JRLoader.java:339)
print_1  |      ... 34 common frames omitted
print_1  | 10:16:37.206 [PrintJobManager-3] DEBUG o.mapfish.print.servlet.job.PrintJob - Print Job 34297b48-e7da-46ae-86ab-a5b68a92eaf3@2d3ae042-dfde-43a6-a212-e66d402644cc completed in 694ms
print_1  | 10:16:38.516 [http-nio-8080-exec-3] ERROR o.m.print.servlet.BaseMapServlet - Error while processing request: java.net.ConnectException: Connection refused (Connection refused)
print_1  | 172.18.0.4 - - - 31/Oct/2017:10:16:38 +0000 "POST /print/oereb/buildreport.pdf HTTP/1.1" 500 99
```
... but calling the logo by using http://localhost:6543/oereb/image/logo/confederation returns me the image file as it should!?

### Titlepage:
- [x] Scalebar size/North arrow are not aligned - I think the width of the scalebar is not as required
- [x] The date format of the creation date should correspond to the Swiss locals: 31.10.2017

### Table of content:
- [x] The overflow for the label for topics touching restrictions has not been set as it should
- [x] for TopicsWithoutData a 'null' is displayed, but it should be blank at least

### Topic pages:
- [x] The area for restrictions should be indicated as integer not decimal
- [x] The font and the font size of the legend entries should be Cadastra 8.5 pt everywhere
- [x] We are missing the legend for the othter objects in the map window. We need to extend the BBOX for the restrictions overlay to the map window bbox, not only the feature bbox
- [x] The complete legend URL overlaps with the bottom border
- [x] The legal provisions URL overlaps with the bottom border

### Glossary:
- [x] The footer of the glossary is glued to the top

There might be other details, but once we fixed all those already there should only be some polishing left... :)

**Comment by voisardf** [comment]
here is the reference PDF: 
[20171031120436_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/1430448/20171031120436_extract.pdf)

**Comment by sbrunner** [comment]
Nice :-)

**Comment by voisardf** [comment]
state of the moment
[20171031040356_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/1431164/20171031040356_extract.pdf)

**Comment by voisardf** [comment]
Other legend will be addressed by PR #306 so there is only the date formatting and the overflow/style issues left :)

**Comment by voisardf** [comment]
One down, two to go... as the full pdf is not required anymore

**Comment by voisardf** [comment]
OK guys, that's the way the final PDF's should look like (get your own on http://sitn.ne.ch/crdppf/ 😉 )
[20171205051512_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/1531939/20171205051512_extract.pdf)
[20171205051606_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/1531941/20171205051606_extract.pdf)
[20171205051934_extract.pdf](https://github.com/camptocamp/pyramid_oereb/files/1531956/20171205051934_extract.pdf)

**Comment by vvmruder** [comment]
@voisardf: Can this issue be closed?

**Comment by voisardf** [comment]
yes
