### ISSUE TITLE
pyramid_oereb no longer buildable on Debian 8

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/pyramid_oereb#602]
pyramid_oereb is no longer buildable on old Debian systems (Debian 8 or older), due to library requirements:

`Downloading/unpacking cryptography>=1.3.4 (from urllib3[secure]==1.23->-r requirements.txt (line 12))
  Downloading cryptography-2.3.1.tar.gz (449kB): 449kB downloaded
  Running setup.py (path:/tmp/pip-build-Y4rmSm/cryptography/setup.py) egg_info for package cryptography
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-Y4rmSm/cryptography/setup.py", line 28, in <module>
        "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-Y4rmSm/cryptography/setup.py", line 28, in <module>

    "cryptography requires setuptools 18.5 or newer, please upgrade to a "

RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools`

**Comment by jwkaltz** [comment]
Fixed in #603 . Note that the fix concerns pyramid_oereb itself. Any pyramid applications including pyramid_oereb as a plugin may need some changes as well, if running on older environments.
