### ISSUE TITLE
Docker wsgi image does not work

### ISSUE THREAD

**Issue by igrcic** [camptocamp/pyramid_oereb#633]
Dear all,

starting from a fresh docker-compose run, wsgi container is throwing the following errors:

[2018-09-05 15:32:45 +0000] [121] [INFO] Starting gunicorn 19.7.1
[2018-09-05 15:32:45 +0000] [121] [INFO] Listening at: http://0.0.0.0:80 (121)
[2018-09-05 15:32:45 +0000] [121] [INFO] Using worker: gthread
[2018-09-05 15:32:45 +0000] [124] [INFO] Booting worker with pid: 124
[2018-09-05 15:32:45 +0000] [125] [INFO] Booting worker with pid: 125
[2018-09-05 15:32:45 +0000] [126] [INFO] Booting worker with pid: 126
[2018-09-05 15:32:45 +0000] [127] [INFO] Booting worker with pid: 127
[2018-09-05 15:32:45 +0000] [128] [INFO] Booting worker with pid: 128
2018-09-05 15:32:46,961 ERROR [c2cwsgiutils.wsgi:23][MainThread] Failed starting the application
Traceback (most recent call last):
  File "/c2cwsgiutils/c2cwsgiutils/wsgi.py", line 21, in create_application
    return get_app(configfile, 'main', options=os.environ)
  File "/usr/local/lib/python3.6/site-packages/pyramid/paster.py", line 28, in get_app
    return loader.get_wsgi_app(name, options)
  File "/usr/local/lib/python3.6/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/app/pyramid_oereb/__init__.py", line 38, in main
    config.include('pyramid_oereb', route_prefix='oereb')
  File "/usr/local/lib/python3.6/site-packages/pyramid/config/__init__.py", line 839, in include
    c(configurator)
  File "/app/pyramid_oereb/__init__.py", line 73, in includeme
    logos = Config.get_logo_config()
  File "/app/pyramid_oereb/lib/config.py", line 363, in get_logo_config
    confederation_logo = ImageRecord(file_adapter.read(logo_dict.get(confederation_key)))
  File "/app/pyramid_oereb/lib/adapter.py", line 105, in read
    raise IOError('Not a file: {0}'.format(filepath))
OSError: Not a file: /app/logo_confederation.png
2018-09-05 15:32:47,055 ERROR [c2cwsgiutils.wsgi:23][MainThread] Failed starting the application
Traceback (most recent call last):
  File "/c2cwsgiutils/c2cwsgiutils/wsgi.py", line 21, in create_application
    return get_app(configfile, 'main', options=os.environ)
  File "/usr/local/lib/python3.6/site-packages/pyramid/paster.py", line 28, in get_app
    return loader.get_wsgi_app(name, options)
  File "/usr/local/lib/python3.6/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/app/pyramid_oereb/__init__.py", line 38, in main
    config.include('pyramid_oereb', route_prefix='oereb')
  File "/usr/local/lib/python3.6/site-packages/pyramid/config/__init__.py", line 839, in include
    c(configurator)
  File "/app/pyramid_oereb/__init__.py", line 73, in includeme
    logos = Config.get_logo_config()
  File "/app/pyramid_oereb/lib/config.py", line 363, in get_logo_config
    confederation_logo = ImageRecord(file_adapter.read(logo_dict.get(confederation_key)))
  File "/app/pyramid_oereb/lib/adapter.py", line 105, in read
    raise IOError('Not a file: {0}'.format(filepath))
OSError: Not a file: /app/logo_confederation.png
2018-09-05 15:32:47,102 ERROR [c2cwsgiutils.wsgi:23][MainThread] Failed starting the application
Traceback (most recent call last):
  File "/c2cwsgiutils/c2cwsgiutils/wsgi.py", line 21, in create_application
    return get_app(configfile, 'main', options=os.environ)
  File "/usr/local/lib/python3.6/site-packages/pyramid/paster.py", line 28, in get_app
    return loader.get_wsgi_app(name, options)
  File "/usr/local/lib/python3.6/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python3.6/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/app/pyramid_oereb/__init__.py", line 38, in main
    config.include('pyramid_oereb', route_prefix='oereb')
  File "/usr/local/lib/python3.6/site-packages/pyramid/config/__init__.py", line 839, in include
    c(configurator)
  File "/app/pyramid_oereb/__init__.py", line 73, in includeme
    logos = Config.get_logo_config()
  File "/app/pyramid_oereb/lib/config.py", line 363, in get_logo_config
    confederation_logo = ImageRecord(file_adapter.read(logo_dict.get(confederation_key)))
  File "/app/pyramid_oereb/lib/adapter.py", line 105, in read
    raise IOError('Not a file: {0}'.format(filepath))

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
gunicorn exited with an error (1), restarting in 1s

**Comment by jwkaltz** [comment]
Dear igrcic,
To try out pyramid_oereb within docker locally, you should do a "make serve". This will include all necessary preparations for starting the docker image.
The following information may be helpful: https://camptocamp.github.io/pyramid_oereb/doc/contrib/contributing.html?highlight=serve

**Comment by igrcic** [comment]
Dear Wolfgang, thank you for the tip, i didnt know one should use the docker images in this way.
