### ISSUE TITLE
Error when loading sample data

### ISSUE THREAD

**Issue by igrcic** [camptocamp/pyramid_oereb#668]
Hello,

after I have created the standar config yaml and inserted the tables, I am trying to load the included sample data set. Unfortunately I am getting some errors:

```
 python $VENV/lib/python3.5/site-packages/pyramid_oereb/standard/load_sample_data.py -c pyramid_oereb_standard.yml
2018-09-26 15:10:10,309 INFO sqlalchemy.engine.base.Engine select version()
2018-09-26 15:10:10,309 INFO sqlalchemy.engine.base.Engine {}
2018-09-26 15:10:10,313 INFO sqlalchemy.engine.base.Engine select current_schema()
2018-09-26 15:10:10,313 INFO sqlalchemy.engine.base.Engine {}
2018-09-26 15:10:10,315 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-09-26 15:10:10,315 INFO sqlalchemy.engine.base.Engine {}
2018-09-26 15:10:10,316 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-09-26 15:10:10,316 INFO sqlalchemy.engine.base.Engine {}
2018-09-26 15:10:10,317 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2018-09-26 15:10:10,317 INFO sqlalchemy.engine.base.Engine {}
Import theme contaminated_public_transport_sites.
Traceback (most recent call last):
  File "$VENV/env/lib/python3.5/site-packages/pyramid_oereb/standard/load_sample_data.py", line 295, in <module>
    _run()
  File "$VENV/env/lib/python3.5/site-packages/pyramid_oereb/standard/load_sample_data.py", line 283, in _run
    SampleData(options.configuration, section=options.section, directory=options.directory).load()
  File "$VENV/env/lib/python3.5/site-packages/pyramid_oereb/standard/load_sample_data.py", line 189, in load
    self._truncate_existing(schema)
  File "$VENV/env/lib/python3.5/site-packages/pyramid_oereb/standard/load_sample_data.py", line 116, in _truncate_existing
    schema=schema.Glossary.__table__.schema,
AttributeError: module 'pyramid_oereb.standard.models.contaminated_public_transport_sites' has no attribute 'Glossary'
```
On the other hand, if I first  create sql file with --sql-file option, the data is successfully imported.

It seems that the loader is trying to truncate the glossary table for contaminated_public_transport_sites schema, which is  not there ( its in the pyramid_oereb_main Schema)

As I am a total öreb noob, I am not sure if I am doing something wrong, or the truncate method is really wrong.

**Comment by jwkaltz** [comment]
Hi igrcic, I had a discussion with Christian yesterday and as I understand it, he is going to contact us to organize a workshop to look at general setup questions together. Therefore, I am closeing this ticket for now.
